# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20171130_0408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publication_date']},
        ),
    ]
